spring:
  application:
    name: digitalfix-ms-login

    #1. Conexion a BD oracle

    datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_URL}
      password: ${SPRING_DATASOURCE_PASSWORD}
      drive-class-name: oracle.jbc.OracleDrive

    jpa:
      database-plataform: org.hibernate.dialect.OracleDialect
      hibernate:
        # Solucion de conflicto: configuracion para control de flyway
        ddl-auto: validate

    #2. configuración de flyway
    flyway:
      enabled: true

    #3. Microsoftentra ID(Resource server)
    cloud:
      azure:
        activate-directory:
          enabled: true
          profile:
            tenant-id: ${AZURE_TENANT_ID}
          credential:
            client-id: ${AZURE_CLIENT_ID}

    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
            audiences: api://${AZURE_CLIENT_ID}