-- Script V1 para la base de datos Oracle de ms-login
CREATE TABLE LOG_AUDITORIA_ACCESO (
                                      ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      USER_ENTRA_ID VARCHAR2(100) NOT NULL, -- Corresponde al 'oid' o 'sub' de Microsoft Entra ID
                                      EVENTO VARCHAR2(50) NOT NULL,         -- 'LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT'
                                      DIRECCION_IP VARCHAR2(45),            -- IPv4 o IPv6
                                      USER_AGENT VARCHAR2(500),             -- Navegador o cliente desde donde se conectó
                                      FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Índice para acelerar búsquedas por usuario e historial
CREATE INDEX IDX_AUDITORIA_USER ON LOG_AUDITORIA_ACCESO(USER_ENTRA_ID);